version: 2.1

orbs:
  node: circleci/node@4.0.0

jobs:
  build_and_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - run:
          name: Install caprover
          command: npm i caprover -g
      # - node/install-packages:
      #     cache-path: node_modules
      #     override-ci-command: npm i
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy